# Generated by Django 3.0.8 on 2020-07-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_main_10',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main_11',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main_12',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main_5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main_6',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main_7',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main_8',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main_9',
        ),
    ]
